// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.
import { Routes } from '@angular/router';
import { IssuePolicy } from './issue-policy/issue-policy';
import { IssuedPolicies } from './issued-policies/issued-policies';

/** One route per `Type: html` entry in uis.md. Spread this into app.routes.ts. */
export const pageRoutes: Routes = [
  { path: 'issue-policy', component: IssuePolicy, title: 'Issue Policy' },
  { path: 'issued-policies', component: IssuedPolicies, title: 'Issued Policies' },
];
