// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.


/** `PolicyHolder` — a nested object on the wire, never a string. */
export interface Policyholder {
  name: string;
  surname: string;
}

/** `PolicyCoverage` — a nested object on the wire, never a string. */
export interface Policycoverage {
  coveragePeriod: string;
  riskList: string[];
}

/** Body of `POST /api/issue-policy` — the `issue-policy` command. */
export interface IssuePolicyPayload {
  policyHolder: Policyholder;
  policyCoverage: Policycoverage;
}

export const ISSUE_POLICY_ENDPOINT = '/api/issue-policy';
