// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import type {
  IssuePolicyPayload,
} from './issue-policy.contracts';
import {
  ISSUE_POLICY_ENDPOINT,
} from './issue-policy.contracts';

@Injectable({ providedIn: 'root' })
export class IssuePolicyApi {
  private readonly http = inject(HttpClient);

  /** `POST` the `issue-policy` command. Resolves to the new aggregate id. */
  issuePolicy(payload: IssuePolicyPayload): Promise<string> {
    return firstValueFrom(this.http.post<string>(ISSUE_POLICY_ENDPOINT, payload));
  }
}
