// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.

import { Component, inject } from '@angular/core';
import type {
  IssuePolicyPayload,
} from './issue-policy.contracts';
import { ISSUE_POLICY_IMPORTS } from './issue-policy.imports';
import { IssuePolicyStore } from './issue-policy.store';

@Component({
  selector: 'app-issue-policy',
  imports: [ISSUE_POLICY_IMPORTS],
  templateUrl: './issue-policy.html',
  styleUrl: './issue-policy.css',
  providers: [IssuePolicyStore],
})
export class IssuePolicy {
  protected readonly store = inject(IssuePolicyStore);

  protected readonly issuePolicyForm: IssuePolicyPayload = {
    policyHolder: {
      name: '',
      surname: '',
    },
    policyCoverage: {
      coveragePeriod: '',
      riskList: [''],
    },
  };
}
