// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.


/** `PolicyHolder` — a nested object on the wire, never a string. */
export interface Policyholder {
  name: string;
  surname: string;
}

/** `PolicyCoverage` — a nested object on the wire, never a string. */
export interface Policycoverage {
  coveragePeriod: string;
  riskList: string[];
}

/** Projection of the `issued-policies` read model. */
export interface IssuedPoliciesView {
  policyKey: string;
  policyNumber: string;
  policyHolder: Policyholder;
  policyCoverage: Policycoverage;
}

export const ISSUED_POLICIES_ENDPOINT = '/api/issued-policies';

/** Query of `GET /api/issued-policies` — filters `issued-policies`. */
export interface IssuedPoliciesSearchCriteria {

}

export const ISSUED_POLICIES_SEARCH_ENDPOINT = '/api/issued-policies';
