// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import type {
  IssuedPoliciesView,
  IssuedPoliciesSearchCriteria,
} from './issued-policies.contracts';
import {
  ISSUED_POLICIES_ENDPOINT,
  ISSUED_POLICIES_SEARCH_ENDPOINT,
} from './issued-policies.contracts';

@Injectable({ providedIn: 'root' })
export class IssuedPoliciesApi {
  private readonly http = inject(HttpClient);

  /** `GET` the `issued-policies` read model. */
  getIssuedPolicies(): Promise<IssuedPoliciesView[]> {
    return firstValueFrom(this.http.get<IssuedPoliciesView[]>(ISSUED_POLICIES_ENDPOINT));
  }

  /** `GET` the `issued-policies` read model, filtered. Same projection as getIssuedPolicies(). */
  searchIssuedPolicies(criteria: IssuedPoliciesSearchCriteria): Promise<IssuedPoliciesView[]> {
    let params = new HttpParams();
    return firstValueFrom(this.http.get<IssuedPoliciesView[]>(ISSUED_POLICIES_SEARCH_ENDPOINT, { params }));
  }
}
