// GENERATED by frontend-development/scripts/codegen — DO NOT EDIT.
// Shape and URLs come from the backend's openapi.json; structure from the event
// model (uis.md / commands.md / readmodels.md). Change those and regenerate.

import { Component, inject, OnInit } from '@angular/core';
import type {
  IssuedPoliciesSearchCriteria,
} from './issued-policies.contracts';
import { ISSUED_POLICIES_IMPORTS } from './issued-policies.imports';
import { IssuedPoliciesStore } from './issued-policies.store';

@Component({
  selector: 'app-issued-policies',
  imports: [ISSUED_POLICIES_IMPORTS],
  templateUrl: './issued-policies.html',
  styleUrl: './issued-policies.css',
  providers: [IssuedPoliciesStore],
})
export class IssuedPolicies implements OnInit {
  protected readonly store = inject(IssuedPoliciesStore);

  ngOnInit(): void {
    void this.store.loadIssuedPolicies();
  }

  protected readonly issuedPoliciesSearchCriteria: IssuedPoliciesSearchCriteria = {
  };
}
